---
name: CI Workflow
on:
  push:
    tags:
      - v*
    branches:
      - main
      - develop
  pull_request:
jobs:
  lint:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
        go:
          - latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: ${{ github.workspace }}/go/src/github.com/alexeyco/rand
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: golangci/golangci-lint-action@v2
        with:
          working-directory: ${{ github.workspace }}/go/src/github.com/alexeyco/rand
          version: latest
  test:
    name: Run tests [go${{ matrix.go }}]
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - ubuntu-latest
        go:
          - latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: ${{ github.workspace }}/go/src/github.com/alexeyco/rand
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version
      - run: go mod vendor
        working-directory: ${{ github.workspace }}/go/src/github.com/alexeyco/rand
      - run: go get github.com/mattn/goveralls
        env:
          GO111MODULE: off
      - run: go test -race -covermode atomic -coverprofile=coverage.out .
        working-directory: ${{ github.workspace }}/go/src/github.com/alexeyco/rand
      - run: goveralls -coverprofile=coverage.out -service=github
        env:
          COVERALLS_TOKEN: ${{ github.token }}
          GIT_BRANCH: ${{ github.head_ref }}
        working-directory: ${{ github.workspace }}/go/src/github.com/alexeyco/rand
